### ISSUE TITLE
Creating Spellbook

### ISSUE THREAD

**Issue by JoshyNeurotic** [Fair-Strides/Fvtt-PF1E-Spellbook-Generator#2]
<img width="549" alt="Screen Shot 2022-10-03 at 8 28 43 PM" src="https://user-images.githubusercontent.com/78518604/193729027-f1c64960-e378-4523-bc17-1f5516e8da40.png">

After opening the generate spellbook tab on the character sheet, dragging (at random) spells from a compendium (this also happens with a empty spellbook as well), then attempting to close or "Create Book" this error happens.   This happens with each of the various spellbook types. 

I Created a new character, no race, class or anything, just a blank sheet.

**Comment by Fair-Strides** [comment]
I should really not be assuming that people have PF-Content turned on, huh? Might need to list it as a dependency like I should have...
