### ISSUE TITLE
Not working with Foundry V10

### ISSUE THREAD

**Issue by Yonman17** [Fair-Strides/Fvtt-PF1E-Spellbook-Generator#6]
PF1e version 9.4, Foundry V 10 -303.
It won't even open on the character sheet and it wont work from the Macro window either.  When using the MACRO window you cannot add spells or a player

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/modules/fair-strides-pf1e-spellbook-generator/module/dialog.mjs:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">dialog.mjs:28</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: undefined. game.i18n.localize(...).format is not a function
[Detected 1 package: fair-strides-pf1e-spellbook-generator]
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at new SpellBookGenUI (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/modules/fair-strides-pf1e-spellbook-generator/module/dialog.mjs:28:99" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">dialog.mjs:28:99</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at SpellBookGenUI.open (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/modules/fair-strides-pf1e-spellbook-generator/module/dialog.mjs:62:3" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">dialog.mjs:62:3</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at showSpellBookGenUI (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/modules/fair-strides-pf1e-spellbook-generator/spellbook-gen.mjs:7:47" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">spellbook-gen.mjs:7:47</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.onclick (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/modules/fair-strides-pf1e-spellbook-generator/spellbook-gen.mjs:17:26" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">spellbook-gen.mjs:17:26</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at HTMLAnchorElement.&lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/scripts/foundry.js:5239:16" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:5239:16</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at HTMLAnchorElement.dispatch (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/scripts/jquery.min.js:2:43064" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">jquery.min.js:2:43064</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at y.handle (<span class="devtools-link" role="link" tabindex="-1" title="https://localhost:30000/scripts/jquery.min.js:2:41048" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">jquery.min.js:2:41048</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | SpellBookGenUI | @ | dialog.mjs:28
-- | -- | -- | --
  | open | @ | dialog.mjs:62
  | showSpellBookGenUI | @ | spellbook-gen.mjs:7
  | onclick | @ | spellbook-gen.mjs:17
  | (anonymous) | @ | foundry.js:5239
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

</span></div>
</body>
</html>

**Comment by Fair-Strides** [comment]
Fixed with v2.1.1
