### ISSUE TITLE
Spellbook Generator cannot actually create a spellbook item or 

### ISSUE THREAD

**Issue by IllogicalBl0x** [Fair-Strides/Fvtt-PF1E-Spellbook-Generator#7]
I am using the most recent update of Spellbook Generator on Pathfinder 9.4, on Foundry v. 11 - Build 308. This was tested with Spellbook Generator as the sole active module. Although I could open the generator from a character sheet, and place and remove spells within, clicking the buttons to actually create the spellbook as an item or save it didn't work. I tried unlinking the actor, and it still didn't work.

**Comment by Fair-Strides** [comment]
Fixed with v2.1.1
